[tool.poetry]
name = "poetic-conan"
version = "0.1.0"
description = " A Poetry plugin integrating a transparent Conan and CMake workflow."

license = "MIT"

authors = [
    "Synodic Software"
]

readme = "README.md"

repository = "https://github.com/Synodic-Software/Synodic-Poetry"
homepage = "https://github.com/Synodic-Software/Synodic-Poetry"


[tool.poetry.dependencies]
python  = "^3.9"
poetry = "^1.1"
conan = "^1.34"
tomlkit = "^0.7"


[tool.poetry.dev-dependencies]
flake8 = "^.8.4"
pytest = "^6.2"
coverage = "^5.5"
black = {version = "^20.8b1", allow-prereleases = true}
pytest-xdist = "^2.2"


[tool.pytest.ini_options]
addopts = "-n8"

[tool.black]


[build-system]
requires        = ["poetry>=1.1"]
build-backend   = "poetry.core.masonry.api"
