[tool.poetry]
name = "conan-for-poetry"
version = "0.0.0"
description = " A Poetry plugin integrating Conan support."

license = "MIT"

authors = [
    "Synodic Software"
]

readme = "README.md"

repository = "https://github.com/Synodic-Software/Conan-for-Poetry"
homepage = "https://github.com/Synodic-Software/Conan-for-Poetry"


[tool.poetry.dependencies]
python  = "^3.8"
poetry = "^1.0"
conan = "^1.21"
click = "^7.0"
toml = "^0.10"


[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
pytest = "^5.3.2"
coverage = "^5.0"
path = "^13.1.0"


#TODO: Remove CLI interface once poetry has plugin support
black = {version = "^19.10b0", allow-prereleases = true}
[tool.poetry.scripts]
conan-poetry = "conan_for_poetry.cli:entrypoint"


[build-system]
requires        = ["poetry>=1.0.0"]
build-backend   = "poetry.masonry.api"
