[tool.poetry]
description = " A Poetry plugin integrating a transparent Conan and CMake workflow."
name = "cppoetry"
version = "0.1.0"

license = "MIT"

authors = [
  "Synodic Software",
]

readme = "README.md"

homepage = "https://github.com/Synodic-Software/CPPoetry"
repository = "https://github.com/Synodic-Software/CPPoetry"

[tool.poetry.dependencies]
python = "^3.9"
conan = "^1.35.2"
poetry = { git = "https://github.com/python-poetry/poetry.git", branch = "master" }
tomlkit = "^0.7.0"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
black = {version = "^20.8b1", allow-prereleases = true}
coverage = "^5.5"
pytest = "^6.2.3"
pytest-xdist = "^2.2.1"
pylint = "^2.7.4"

[tool.poetry.plugins."poetry.application.plugin"]
cppoetry = "cppoetry.plugin:SynodicPlugin"

[tool.poetry.scripts]
cppoetry = 'cppoetry.console:cli'

[tool.pytest.ini_options]
#addopts = "-n auto"

[tool.black]
line-length = 120

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "120"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry>=1.1.6"]
