[project]
description = " A Python package manager agnostic plugin integrating a transparent Conan and CMake workflow."
name = "cppython"

license = "MIT"

authors = [
  "Synodic Software",
]

readme = "README.md"

homepage = "https://github.com/Synodic-Software/CPPython"
repository = "https://github.com/Synodic-Software/CPPython"

dynamic = ["version"]

requires-python = ">=3.10"

dependencies = [
    "click~=8.0",
    "cmake~=3.22",
    "pydantic~=1.8",
    "tomlkit~=0.7",
]

[tool.pdm]
version = {use_scm = true}

[tool.pdm.dev-dependencies]
lint = [
  "black<22,>=21.11b1",
  "pylint~=2.12",
]
test = [
  "pytest~=6.2",
  "pytest-cov~=3.0",
  "pytest-mock~=3.6",
  "pytest-xdist~=2.4",
]

[tool.poetry.scripts]
cppython = 'cppython.plugins.interface.console:cli'

# Register the testing information with pytest
[tool.poetry.plugins.pytest11]
pytest_cppython = "cppython.plugins.test.pytest"

[tool.pytest.ini_options]
addopts = "-n auto"
testpaths = [
  "tests",
]

[tool.black]
line-length = 120

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "120"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[build-system]
build-backend = "pdm.pep517.api"
requires = ["pdm-pep517"]
