[tool.poetry]
description = " A Python package manager agnostic plugin integrating a transparent Conan and CMake workflow."
name = "cppython"
version = "0.1.0"

license = "MIT"

authors = [
  "Synodic Software",
]

readme = "README.md"

homepage = "https://github.com/Synodic-Software/CPPython"
repository = "https://github.com/Synodic-Software/CPPython"

[tool.poetry.dependencies]
python = "^3.9"
conan = "^1.36.0"
poetry = { git = "https://github.com/python-poetry/poetry.git", branch = "master" }
tomlkit = "^0.7.0"
toml = "^0.10.2"
click = "^7.1.2"
cerberus = "^1.3.4"
pdm = "^1.5.2"

[tool.poetry.dev-dependencies]
black = {version = "^21.5b0", allow-prereleases = true}
coverage = "^5.5"
pytest = "^6.2.4"
pytest-xdist = "^2.2.1"
pylint = "^2.8.2"

[tool.poetry.plugins."poetry.application.plugin"]
cppython = "cppython.entry_points.poetry:SynodicPlugin"

[tool.poetry.scripts]
cppython = 'cppython.entry_points.console:cli'

[project.entry-points.pdm]
hello = "cppython.entry_points:hello_plugin"

[tool.pytest.ini_options]
addopts = "-n auto"
testpaths = [
    "tests"
]

[tool.black]
line-length = 120

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "120"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry>=1.1.6"]
