[tool.poetry]
name = "poetic-conan"
version = "0.1.0"
description = " A Poetry plugin integrating a transparent Conan and CMake workflow."

license = "MIT"

authors = [
    "Synodic Software"
]

readme = "README.md"

repository = "https://github.com/Synodic-Software/Synodic-Poetry"
homepage = "https://github.com/Synodic-Software/Synodic-Poetry"


[tool.poetry.dependencies]
python  = "^3.8"
poetry = "^1.0"
conan = "^1.22"
tomlkit = "^0.5.8"


[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
pytest = "^5.3.2"
coverage = "^5.0"
black = {version = "^19.10b0", allow-prereleases = true}
pytest-xdist = "^1.31.0"


[build-system]
requires        = ["poetry>=1.0.0"]
build-backend   = "poetry.masonry.api"
