[tool.poetry]
description = " A Poetry plugin integrating a transparent Conan and CMake workflow."
name = "poetic-conan"
version = "0.1.0"

license = "MIT"

authors = [
  "Synodic Software",
]

readme = "README.md"

homepage = "https://github.com/Synodic-Software/Synodic-Poetry"
repository = "https://github.com/Synodic-Software/Synodic-Poetry"

[tool.poetry.dependencies]
conan = "^1.34"
poetry = "^1.1"
python = "^3.9"
tomlkit = "^0.7"

[tool.poetry.dev-dependencies]
black = {version = "^20.8b1", allow-prereleases = true}
coverage = "^5.5"
flake8 = "^.8.4"
pytest = "^6.2"
pytest-xdist = "^2.2"

[tool.pytest.ini_options]
addopts = "-n auto"

[tool.black]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry>=1.1"]
