[tool.poetry]
description = " A Python package manager agnostic plugin integrating a transparent Conan and CMake workflow."
name = "cppython"
version = "0.1.0"

license = "MIT"

authors = [
  "Synodic Software",
]

readme = "README.md"

homepage = "https://github.com/Synodic-Software/CPPython"
repository = "https://github.com/Synodic-Software/CPPython"

[tool.poetry.dependencies]
click = "^8.0.1"
pydantic = "^1.8.2"
python = "^3.9"
tomlkit = "^0.7.2"
cmake = "^3.21.1"

[tool.poetry.dev-dependencies]
black = {version = "^21.7b0", allow-prereleases = true}
pylint = "^2.9.6"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
pytest-mock = "^3.6.1"
pytest-xdist = "^2.3.0"

[tool.poetry.scripts]
cppython = 'cppython.plugins.interface.console:cli'

[tool.pytest.ini_options]
addopts = "-n auto"
testpaths = [
  "tests",
]

[tool.black]
line-length = 120

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "120"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry>=1.1.7"]
