name: Integration

on:
  pull_request:
    types: [opened, edited]

jobs:

  label_pull_request:

    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  install:

    runs-on: ubuntu-latest
    strategy:
      matrix: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        python-version: [3.8]

    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/checkout@v2

    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.2

    - name: Install Dependencies
      run: poetry install

  test:

    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        python-version: [3.8]

    steps:

    - name: Test
      run: pytest tests/
    
  format:

    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        python-version: [3.8]

    steps:

    - name: Format
      run: flake8


