name: Update Dependencies

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-dependencies:
    if: github.repository_owner == 'Synodic-Software'
    uses: synodic-software/.github/.github/workflows/python-dependency.yml@stable