name: Publish Python Package
on:
  release:
    types: [published]

jobs:
  publish_release:
    if: github.repository_owner == 'Synodic-Software'
    uses: synodic-software/.github/.github/workflows/python-publish.yml@stable
    with:
      repository_url: https://upload.pypi.org/legacy/
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
